version: '3.8'
services:
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - ml-model

  ml-model:
    build: ./ml-model
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./ml-model:/app
    ports:
      - "8001:8001"

volumes:
  db_data:
  grafana_data:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - api
      - ml-model

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
