apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-analyzer-config
  namespace: sentiment-analyzer
data:
  DATABASE_NAME: "sentiment"
  ML_MODEL_URL: "http://ml-model-service:8001/analyze"
  # Add environment-specific configurations
  ENVIRONMENT: "private-cloud"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "http://sentiment-analyzer.local,http://localhost:5173"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: sentiment-analyzer
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n 'your-value' | base64
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password
  mongodb-url: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9zZW50aW1lbnQ/YXV0aFNvdXJjZT1hZG1pbg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    scrape_configs:
      - job_name: 'api-service'
        static_configs:
          - targets: ['api-service.sentiment-analyzer.svc.cluster.local:8000']
        metrics_path: '/metrics'
        scrape_interval: 10s
      
      - job_name: 'ml-model-service'
        static_configs:
          - targets: ['ml-model-service.sentiment-analyzer.svc.cluster.local:8001']
        metrics_path: '/metrics'
        scrape_interval: 10s
      
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            target_label: __address__
            replacement: '${1}:9100'
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  sentiment-analyzer-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Sentiment Analyzer Metrics",
        "tags": ["sentiment", "microservices"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "legendFormat": "{{service}}"
              }
            ]
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
                "legendFormat": "95th percentile"
              }
            ]
          },
          {
            "id": 3,
            "title": "Error Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(http_requests_total{status=~\"5..\"}[5m])",
                "legendFormat": "Error Rate"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }
