# MongoDB Deployment with OpenStack Cinder Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-openstack
  labels:
    type: cinder
spec:
  storageClassName: cinder-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s-storage/mongodb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-openstack
  namespace: sentiment-analyzer
spec:
  storageClassName: cinder-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-openstack
  namespace: sentiment-analyzer
  labels:
    app: mongodb
    platform: openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      platform: openstack
  template:
    metadata:
      labels:
        app: mongodb
        platform: openstack
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-storage
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sentiment-analyzer-config
              key: DATABASE_NAME
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /data/configdb
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc-openstack
      - name: mongodb-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-openstack
  namespace: sentiment-analyzer
  labels:
    app: mongodb
    platform: openstack
spec:
  selector:
    app: mongodb
    platform: openstack
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  type: ClusterIP
---
# StorageClass for OpenStack Cinder
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true